apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: ccreate-aws-vm-template
  title: create-aws-vm Template
  description: Create an AWS EC2 instance using Terraform
  tags:
    - terraform
    - github
steps:
  - id: terraform-init
    name: Terraform Init
    command: |
      cd ${{ input.workDir }}/terraform
      terraform init
  - id: terraform-plan
    name: Terraform Plan
    command: |
      cd ${{ input.workDir }}/terraform
      terraform plan -var="region=${{ input.parameters.region }}"
  - id: terraform-apply
    name: Terraform Apply
    command: |
      cd ${{ input.workDir }}/terraform
      terraform apply -auto-approve -var="region=${{ input.parameters.region }}"
