apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: vm-classic
  title: Create a new Virtual Machine
  description: |
    A template for creating a new Virtual Machine via gitlab.
  tags:
  - gitlab
  - terraform
  - aws
spec:
  owner: group:infrastructure
  type: infrastructure
  parameters:
  - title: Configure Pulumi template
    required:
    - projectname
    - buildversion
    - environment
    properties:
      projectname:
        title: Organization
        type: string
        description: The Pulumi organization to use for the Pulumi project
      buildversion:
        title: Region
        type: string
        description: |
          The region to deploy the virtual machine to
      environment:
        title: Select stack
        type: string
        enum:
        - dev
        - staging
        - prod
        enumNames:
        - Development
        - Staging
        - Production
        description: The pulumi stack to use
  - title: Choose a GitHub repository location
    required:
    - repoUrl
    properties:
      repoUrl:
        title: Repository Location
        type: string
        ui:field: RepoUrlPicker
        ui:options:
          allowedHosts:
          - github.com
  steps:
  - id: pulumi-new-component
    name: Create new Pulumi component
    action: gitlab:pipeline:invoke
    input:
      name: ${{parameters.projectname}}
      description: ${{parameters.buildversion}}
      stack: ${{parameters.environment}}


  - id: wait
    name: Wait for template to be fetched
    action: debug:wait
    input:
      seconds: 10
      
  - id: template
    name: Render the Backstage template
    action: fetch:template
    input:
      url: ./template
      values:
        projectname: "${{ parameters.projectname }}"
        buildversion: ${{ parameters.buildversion }}
        environment: ${{ parameters.environment }}

  - id: publish
    name: Publish to GitHub
    action: publish:github
    input:
      allowedHosts: ["github.com"]
      repoVisibility: public
      description: "This repository contains the infrastructure code for the ${{ parameters.projectname }} component"
      repoUrl: ${{ parameters.repoUrl }}
      defaultBranch: main
      requiredApprovingReviewCount: 0
      protectDefaultBranch: false

  - id: wait-again
    name: Wait for the repository to be created
    action: debug:wait
    input:
      seconds: 5

  - id: register
    name: Registering the Catalog Info Component
    action: catalog:register
    input:
      repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
      catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
    - title: Open the Source Code Repository
      url: ${{ steps['publish'].output.repoContentsUrl }}
    - title: Open the Catalog Info Component
      icon: catalog
      entityRef: ${{ steps['register'].output.entityRef }}
    - title: IP Address
      url: ${{ steps['pulumi-deploy-infrastructure'].output.ip }}
    - title: URL
      url: ${{ steps['pulumi-deploy-infrastructure'].output.url }}
