apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-vm-infra-aws
  title: Create vm on aws
  description: Create a new vm on aws
  tags:
    - aws
    - terraform
spec:
  owner: dpogula
  type: infrastructure
  parameters:
    - title: Provide some simple information
      required:
        - region
        - owner
      properties:
        region:
          title: Name
          type: string
          description: provide the aws region to provision infra
          ui:field: EntityNamePicker

       
  steps:
    - id: terraform-init
      name: Terraform Init
      action: terraforminit:init
      command: |
        cd ${{ input.workDir }}/terraform
        terraform init
    - id: terraform-plan
      name: Terraform Plan
      action: terraformplan:plan
      command: |
        cd ${{ input.workDir }}/terraform
        terraform plan -var="region=${{ input.parameters.region }}"
    - id: terraformapply:apply
      name: Terraform Apply
      action: terraform:template
      command: |
        cd ${{ input.workDir }}/terraform
        terraform apply -auto-approve -var="region=${{ input.parameters.region }}"

  
