apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: vm-on-aws-tf-backstage
  title: Create a new Virtual Machine on AWS
  description: |
    A template for creating a new Virtual Machine via terraform.
  tags:
  - terraform
  - vm
  - aws
spec:
  owner: group:infrastructure
  type: infrastructure
  parameters:
  - title: Provide project information
    required:
    - projectname
    - buildversion
    - environment
    properties:
      projectname:
        title: Project Name
        type: string
        ui:field: EntityPicker
        description: Unique name of the terraform-aws project.
        enum:
        - ProjectA
        - ProjectB
        - ProjectC
        default: ProjectA
        
      buildversion:
        title: Build Version
        type: string
        ui:field: EntityPicker
        description: build version of the project.
        enum:
        - v1.1
        default: v1.o
        
      environment:
        title: Environment Stack
        type: string
        ui:field: EntityPicker
        description: environment selection
        enum:
        - Development
        - Staging
        - Production
        default: Development
  steps:
  - id: invoke-gitlab-ci-yaml
    name: Invoke GitLab CI Yaml with input parameters
    action: gitlab:pipeline:invoke
    input:
      project_name: ${{parameters.projectname}}
      build_version: ${{parameters.buildversion}}
      environment: ${{parameters.environment}}
      handler: 'file://./actions/invokePipeline2.ts'
      description: Action to invoke GitLab pipeline
      type: button
      icon: play

