apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-react-app-template
  title: Create React App Template
  description: Create a new CRA website project
  tags:
    - react
    - cra
spec:
  owner: dpogula
  type: infrastructure
  parameters:
    - title: Provide some simple information
      required:
        - region
        - owner
      properties:
        region:
          title: Name
          type: string
          description: Unique name of the component
          ui:field: EntityNamePicker

        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
  steps:
    - id: terraform-init
      name: Terraform Init
      command: |
        cd ${{ input.workDir }}/terraform
        terraform init
    - id: terraform-plan
      name: Terraform Plan
      command: |
        cd ${{ input.workDir }}/terraform
        terraform plan -var="region=${{ input.parameters.region }}"
    - id: terraform-apply
      name: Terraform Apply
      command: |
        cd ${{ input.workDir }}/terraform
        terraform apply -auto-approve -var="region=${{ input.parameters.region }}"

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in catalog
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
